/**
 * 种子数据
 * 每个分类 100+ 条活动建议
 */

const categoriesData = [
  { name: '独处', icon: '🧘', description: '享受属于自己的时光', sort_order: 1 },
  { name: '情侣', icon: '💑', description: '让爱在日常中升温', sort_order: 2 },
  { name: '好友', icon: '🎉', description: '三五好友，快乐加倍', sort_order: 3 },
  { name: '发现', icon: '🗺️', description: '发现身边的美好', sort_order: 4 },
];

// ========== 独处活动（100+条）==========
const soloActivities = [
  { title: '去咖啡馆坐1小时', description: '找一家安静的咖啡馆，点一杯拿铁，享受独处时光', tags: '["放松","咖啡","日常"]', mood_tags: '["平静","无聊"]', icon: '☕' },
  { title: '学习一项新技能', description: '在B站或YouTube找一个感兴趣的教程，花1小时学习', tags: '["学习","成长"]', mood_tags: '["平静"]', icon: '📚' },
  { title: '散步30分钟', description: '在家附近散步，不带手机，用心感受周围', tags: '["运动","放松"]', mood_tags: '["平静","无聊"]', icon: '🚶' },
  { title: '看一部电影', description: '选一部评分8.0以上的电影，沉浸其中', tags: '["电影","放松"]', mood_tags: '["平静","无聊"]', icon: '🎬' },
  { title: '做一顿精致的晚餐', description: '为自己做一顿用心的晚餐，摆盘拍照', tags: '["烹饪","生活"]', mood_tags: '["平静","开心"]', icon: '🍳' },
  { title: '写一篇日记', description: '记录今天的三件小事，感恩生活中的美好', tags: '["写作","反思"]', mood_tags: '["平静"]', icon: '📝' },
  { title: '整理房间', description: '断舍离一小时，让空间焕然一新', tags: '["整理","生活"]', mood_tags: '["平静"]', icon: '🏠' },
  { title: '读一本纸质书', description: '放下手机，拿起一本纸质书，读30页', tags: '["阅读","放松"]', mood_tags: '["平静"]', icon: '📖' },
  { title: '泡一个热水澡', description: '点上香薰蜡烛，放点轻音乐，好好泡个澡', tags: '["放松","自我关怀"]', mood_tags: '["平静"]', icon: '🛁' },
  { title: '做一个手工DIY', description: '折纸、编织、拼图…选一种手工活，专注完成', tags: '["手工","创造"]', mood_tags: '["平静","无聊"]', icon: '🎨' },
  { title: '给植物浇水修剪', description: '照料家里的绿植，修剪枯叶，换水施肥', tags: '["园艺","生活"]', mood_tags: '["平静"]', icon: '🪴' },
  { title: '冥想15分钟', description: '打开冥想App，闭上眼睛，专注呼吸', tags: '["冥想","放松"]', mood_tags: '["平静"]', icon: '🧘' },
  { title: '听一张完整的专辑', description: '选一张喜欢的专辑，从头到尾完整听完', tags: '["音乐","放松"]', mood_tags: '["平静","开心"]', icon: '🎵' },
  { title: '练习书法', description: '准备好笔墨纸砚，静心写一篇字', tags: '["书法","艺术"]', mood_tags: '["平静"]', icon: '✍️' },
  { title: '去看一场展览', description: '搜索附近的美术馆或博物馆，接受艺术熏陶', tags: '["艺术","外出"]', mood_tags: '["平静","开心"]', icon: '🏛️' },
  { title: '做一个数字断舍离', description: '清理手机App、电脑桌面、邮箱订阅', tags: '["整理","数字生活"]', mood_tags: '["平静"]', icon: '📱' },
  { title: '画一幅画', description: '不用追求完美，随便涂鸦也是表达', tags: '["绘画","创造"]', mood_tags: '["平静","开心"]', icon: '🎨' },
  { title: '制定下周计划', description: '用笔记本规划下周的工作和生活', tags: '["规划","效率"]', mood_tags: '["平静"]', icon: '📋' },
  { title: '学习做一道新菜', description: '打开下厨房App，学做一道从未尝试过的菜', tags: '["烹饪","学习"]', mood_tags: '["平静","开心"]', icon: '🍲' },
  { title: '去公园晒太阳', description: '带上野餐垫，去公园草坪躺一会儿', tags: '["户外","放松"]', mood_tags: '["开心","平静"]', icon: '☀️' },
  { title: '整理手机相册', description: '删除重复照片，精选100张打印成册', tags: '["整理","回忆"]', mood_tags: '["平静"]', icon: '📸' },
  { title: '做一个在线心理测试', description: '更好地了解自己的性格和情绪', tags: '["自我探索"]', mood_tags: '["平静","无聊"]', icon: '🔍' },
  { title: '尝试一小时的断网生活', description: '关闭所有电子设备，纯手工度过一小时', tags: '["数字排毒"]', mood_tags: '["平静"]', icon: '🔌' },
  { title: '去图书馆坐一下午', description: '在图书馆随便翻翻书，享受安静的氛围', tags: '["阅读","外出"]', mood_tags: '["平静"]', icon: '📚' },
  { title: '学习三个新单词', description: '用单词卡或App学三个外语单词并造句', tags: '["学习","语言"]', mood_tags: '["平静"]', icon: '🔤' },
  { title: '做一次面部护理', description: '敷面膜、涂精华，给自己做个SPA', tags: '["护肤","自我关怀"]', mood_tags: '["平静","开心"]', icon: '💆' },
  { title: '重新布置房间格局', description: '移动家具，改变空间布局，换个心情', tags: '["家居","创造"]', mood_tags: '["开心"]', icon: '🪑' },
  { title: '写一封信给未来的自己', description: '写下对一年后自己的期待和祝福', tags: '["写作","自我探索"]', mood_tags: '["平静"]', icon: '💌' },
  { title: '学习基础瑜伽', description: '跟着视频做30分钟基础瑜伽', tags: '["运动","放松"]', mood_tags: '["平静"]', icon: '🧘‍♀️' },
  { title: '做一个梦想板', description: '用杂志剪贴或Pinterest做一个愿景板', tags: '["规划","创造"]', mood_tags: '["开心"]', icon: '🎯' },
  { title: '整理衣橱并搭配新造型', description: '把不穿的衣服捐掉，用现有衣物搭配新造型', tags: '["穿搭","整理"]', mood_tags: '["开心"]', icon: '👗' },
  { title: '去花店买一束花', description: '选一束喜欢的鲜花，回家插好', tags: '["生活","外出"]', mood_tags: '["开心","平静"]', icon: '💐' },
  { title: '学唱一首新歌', description: '打开歌词，跟着音乐学唱一首喜欢的歌', tags: '["音乐","学习"]', mood_tags: '["开心"]', icon: '🎤' },
  { title: '看一部纪录片', description: '选一个感兴趣的题材，拓展认知边界', tags: '["学习","电影"]', mood_tags: '["平静"]', icon: '🎥' },
  { title: '用脚步丈量城市', description: '选一个没去过的街区，暴走两小时', tags: '["探索","运动"]', mood_tags: '["冒险","开心"]', icon: '👣' },
  { title: '做一个时间记录', description: '用一天时间记录每件事花的时间', tags: '["效率","反思"]', mood_tags: '["平静"]', icon: '⏱️' },
  { title: '尝试正念饮食', description: '选一种食物，慢慢品尝，感受它的味道和口感', tags: '["正念","生活"]', mood_tags: '["平静"]', icon: '🍽️' },
  { title: '自学一个魔术', description: '找一个简单的魔术教程，练熟了给朋友表演', tags: '["学习","娱乐"]', mood_tags: '["开心"]', icon: '🪄' },
  { title: '去天台看日落', description: '找一个高处，静静看一场完整的日落', tags: '["自然","放松"]', mood_tags: '["平静","浪漫"]', icon: '🌅' },
  { title: '整理自己的知识库', description: '用Notion或飞书整理学过的知识点', tags: '["效率","学习"]', mood_tags: '["平静"]', icon: '🗂️' },
  { title: '做一次深层拉伸', description: '15分钟全身拉伸，放松每一块肌肉', tags: '["运动","放松"]', mood_tags: '["平静"]', icon: '🤸' },
  { title: '烘焙一份甜点', description: '尝试做曲奇饼干或布朗尼蛋糕', tags: '["烘焙","烹饪"]', mood_tags: '["开心"]', icon: '🍪' },
  { title: '清理电脑文件', description: '整理桌面、分类文件夹、清理缓存', tags: '["整理","效率"]', mood_tags: '["平静"]', icon: '💻' },
  { title: '学习理财知识', description: '读一篇理财文章，了解一个投资概念', tags: '["学习","理财"]', mood_tags: '["平静"]', icon: '💰' },
  { title: '写感恩清单', description: '写下10件让你感恩的人和事', tags: '["写作","正念"]', mood_tags: '["开心","平静"]', icon: '🙏' },
  { title: '去文具店逛逛', description: '逛文具店，买一支好用的笔或本子', tags: '["购物","外出"]', mood_tags: '["开心","无聊"]', icon: '🖊️' },
  { title: '学习折纸艺术', description: '跟着教程折几只纸鹤或纸花', tags: '["手工","学习"]', mood_tags: '["平静"]', icon: '🦢' },
  { title: '做一个能量早餐', description: '提前准备一份营养丰富的早餐', tags: '["烹饪","生活"]', mood_tags: '["开心"]', icon: '🥗' },
  { title: '听一场播客', description: '选一个感兴趣的播客，边散步边听', tags: '["学习","放松"]', mood_tags: '["平静","无聊"]', icon: '🎧' },
  { title: '设计自己的名片', description: '用Canva设计一张个人名片', tags: '["设计","创造"]', mood_tags: '["平静","开心"]', icon: '🃏' },
  { title: '去独立书店探店', description: '找到一家独立书店，淘一本好书', tags: '["阅读","外出"]', mood_tags: '["开心","平静"]', icon: '📚' },
  { title: '学习基础摄影构图', description: '了解三分法、对称构图等基本技巧', tags: '["学习","摄影"]', mood_tags: '["平静"]', icon: '📷' },
  { title: '做一个睡前仪式', description: '调暗灯光、点香薰、喝杯热牛奶、放下手机', tags: '["睡眠","自我关怀"]', mood_tags: '["平静"]', icon: '🌙' },
  { title: '去菜市场买菜做饭', description: '逛菜市场感受烟火气，买新鲜食材回家做饭', tags: '["烹饪","生活"]', mood_tags: '["开心"]', icon: '🧺' },
  { title: '写一首诗', description: '不用押韵，不用华丽辞藻，写下随机岛感受', tags: '["写作","创造"]', mood_tags: '["平静","浪漫"]', icon: '✒️' },
  { title: '制作一份个人年度总结', description: '整理这一年的重要时刻和成长', tags: '["反思","写作"]', mood_tags: '["平静"]', icon: '📊' },
  { title: '学习打一个领带/丝巾', description: '学会一种新的领带或丝巾系法', tags: '["学习","穿搭"]', mood_tags: '["平静"]', icon: '👔' },
  { title: '做一次断舍离大扫除', description: '每件物品问自己：过去一年用过吗？', tags: '["整理","生活"]', mood_tags: '["平静"]', icon: '🗑️' },
  { title: '去河边或海边发呆', description: '找个有水的地方，什么都不做，发一会儿呆', tags: '["放松","自然"]', mood_tags: '["平静"]', icon: '🌊' },
  { title: '学习冲泡手冲咖啡', description: '买一套简易手冲工具，学习正确冲泡方法', tags: '["咖啡","学习"]', mood_tags: '["平静","开心"]', icon: '☕' },
  { title: '整理收藏夹', description: '清理浏览器收藏夹，重新分类整理', tags: '["整理","效率"]', mood_tags: '["平静"]', icon: '📌' },
  { title: '去唱片店淘碟', description: '找一家唱片店，淘几张黑胶或CD', tags: '["音乐","外出"]', mood_tags: '["开心","平静"]', icon: '💿' },
  { title: '做一个愿景冥想', description: '闭上眼睛，想象理想生活的每一个细节', tags: '["冥想","自我探索"]', mood_tags: '["平静"]', icon: '🌟' },
  { title: '尝试画水彩画', description: '买一套入门水彩工具，跟着教程画一幅', tags: '["绘画","学习"]', mood_tags: '["平静","开心"]', icon: '🖌️' },
  { title: '学习急救知识', description: '了解CPR和海姆立克急救法', tags: '["学习","实用"]', mood_tags: '["平静"]', icon: '🏥' },
  { title: '去一个没去过的地铁站', description: '随机选一个地铁站，下车探索周边', tags: '["探索","冒险"]', mood_tags: '["冒险","开心"]', icon: '🚇' },
  { title: '做一套完整的护肤流程', description: '清洁→面膜→精华→面霜，一步不落', tags: '["护肤","自我关怀"]', mood_tags: '["平静","开心"]', icon: '✨' },
  { title: '整理密码管理器', description: '更新密码，开启双因素认证', tags: '["安全","整理"]', mood_tags: '["平静"]', icon: '🔐' },
  { title: '学习基础调酒', description: '学做一款简单的鸡尾酒或无酒精饮品', tags: '["学习","生活"]', mood_tags: '["开心"]', icon: '🍸' },
  { title: '去24小时书店过夜', description: '找一家24小时书店，深夜阅读', tags: '["阅读","冒险"]', mood_tags: '["冒险","浪漫"]', icon: '🌃' },
  { title: '做一次衣物护理', description: '清理鞋子、熨烫衬衫、去球器处理毛衣', tags: '["整理","生活"]', mood_tags: '["平静"]', icon: '👞' },
  { title: '学习星座知识', description: '了解自己的星盘，认识上升星座和月亮星座', tags: '["学习","兴趣"]', mood_tags: '["无聊","平静"]', icon: '⭐' },
  { title: '制作一份旅行计划', description: '即使暂时不去，规划一条梦想旅行路线', tags: '["规划","旅行"]', mood_tags: '["开心"]', icon: '✈️' },
  { title: '临摹一幅名画', description: '选一幅喜欢的画作，临摹学习', tags: '["绘画","艺术"]', mood_tags: '["平静"]', icon: '🖼️' },
  { title: '更新简历和LinkedIn', description: '梳理最近的成就，更新个人资料', tags: '["职业发展"]', mood_tags: '["平静"]', icon: '💼' },
  { title: '去按摩店做一次按摩', description: '预约一次专业按摩，放松身体', tags: '["放松","自我关怀"]', mood_tags: '["平静","开心"]', icon: '💆‍♂️' },
  { title: '做一个时间胶囊', description: '收集一些代表当下的物品，封存起来', tags: '["创造","回忆"]', mood_tags: '["平静","浪漫"]', icon: '⏳' },
  { title: '学习识别10种植物', description: '用识花App认识身边的植物', tags: '["学习","自然"]', mood_tags: '["平静","开心"]', icon: '🌿' },
  { title: '重看一部童年动画', description: '找回童年的快乐和纯粹', tags: '["怀旧","放松"]', mood_tags: '["开心","无聊"]', icon: '📺' },
  { title: '整理药品箱', description: '过期药品清理，常用药补充', tags: '["整理","实用"]', mood_tags: '["平静"]', icon: '💊' },
  { title: '写一篇书评或影评', description: '分享你最近看的一本书或一部电影的感受', tags: '["写作","分享"]', mood_tags: '["平静"]', icon: '⭐' },
  { title: '尝试一天素食', description: '挑战一日三餐全素食', tags: '["饮食","挑战"]', mood_tags: '["平静","冒险"]', icon: '🥬' },
  { title: '学习基础缝纫', description: '学会缝扣子和简单修补', tags: '["学习","实用"]', mood_tags: '["平静"]', icon: '🧵' },
  { title: '去古着店淘宝', description: '逛古着店，寻找独一无二的衣物', tags: '["购物","探索"]', mood_tags: '["冒险","开心"]', icon: '👗' },
  { title: '制作一份专属歌单', description: '按场景制作歌单：读书时、运动时、失眠时', tags: '["音乐","创造"]', mood_tags: '["开心","平静"]', icon: '🎼' },
  { title: '去早市感受清晨', description: '5点起床，去早市看看城市苏醒的样子', tags: '["生活","探索"]', mood_tags: '["冒险","开心"]', icon: '🌄' },
  { title: '学习用筷子做发型', description: '看视频学习一种盘发技巧', tags: '["学习","美妆"]', mood_tags: '["开心","无聊"]', icon: '💇' },
  { title: '给自己写一封情书', description: '写下你欣赏自己的地方，对自己说爱', tags: '["写作","自我关怀"]', mood_tags: '["平静","浪漫"]', icon: '💝' },
  { title: '做一道家乡菜', description: '复刻一道小时候最爱的家乡味道', tags: '["烹饪","怀旧"]', mood_tags: '["开心","平静"]', icon: '🏡' },
  { title: '去旧货市场寻宝', description: '在跳蚤市场寻找有趣的旧物', tags: '["探索","购物"]', mood_tags: '["冒险","开心"]', icon: '🔍' },
  { title: '学习基础围棋', description: '了解围棋规则，下一盘入门对局', tags: '["学习","棋类"]', mood_tags: '["平静"]', icon: '♟️' },
  { title: '整理微信好友列表', description: '清理长期不联系的好友，分组管理', tags: '["整理","社交"]', mood_tags: '["平静"]', icon: '👥' },
  { title: '去茶馆品茶', description: '找一家茶馆，学习品鉴不同茶叶', tags: '["茶文化","外出"]', mood_tags: '["平静","开心"]', icon: '🍵' },
  { title: '做一个情绪日记', description: '记录今天什么时候开心、焦虑、愤怒以及原因', tags: '["写作","自我探索"]', mood_tags: '["平静"]', icon: '📔' },
  { title: '学习魔术气球', description: '学做气球小狗和小花', tags: '["手工","学习"]', mood_tags: '["开心","无聊"]', icon: '🎈' },
  { title: '去旧书摊淘书', description: '在街角的旧书摊，用低价淘到好书', tags: '["阅读","外出"]', mood_tags: '["开心","平静"]', icon: '📚' },
  { title: '做一个10年目标规划', description: '写下10年后你希望成为什么样的人', tags: '["规划","自我探索"]', mood_tags: '["平静"]', icon: '🎯' },
  { title: '录制一段自己的声音', description: '读一段喜欢的文字，录下来听听', tags: '["声音","创造"]', mood_tags: '["平静","无聊"]', icon: '🎙️' },
  { title: '去宠物店看小动物', description: '即使不买，看看可爱的小动物也很治愈', tags: '["动物","放松"]', mood_tags: '["开心","无聊"]', icon: '🐱' },
  { title: '学习国际象棋规则', description: '了解基本走法，和电脑下一盘', tags: '["学习","棋类"]', mood_tags: '["平静"]', icon: '♚' },
  { title: '整理云盘文件', description: '清理网盘重复文件，建立分类', tags: '["整理","效率"]', mood_tags: '["平静"]', icon: '☁️' },
  { title: '做一个手账页面', description: '用纸胶带、贴纸装饰一页手账', tags: '["手工","创造"]', mood_tags: '["开心","平静"]', icon: '📒' },
  { title: '学习基础心理学', description: '了解一个心理学概念，比如"锚定效应"', tags: '["学习","心理学"]', mood_tags: '["平静"]', icon: '🧠' },
  { title: '去天台看星星', description: '找一个光污染少的地方，仰望星空', tags: '["自然","浪漫"]', mood_tags: '["浪漫","平静"]', icon: '✨' },
  { title: '做一次志愿者', description: '找一个本地的志愿者活动，付出善意', tags: '["公益","社交"]', mood_tags: '["开心"]', icon: '🤝' },
  { title: '学跳一支舞', description: '在镜子前，跟着视频学跳一支简单的舞', tags: '["舞蹈","运动"]', mood_tags: '["开心"]', icon: '💃' },
];

// ========== 情侣活动（100+条）==========
const coupleActivities = [
  { title: '一起去便利店互相挑零食', description: '每人给对方挑三样零食，不能超过预算', tags: '["便利店","约会"]', mood_tags: '["开心","浪漫"]', icon: '🛒' },
  { title: '一起拍一组情侣照片', description: '找一面好看的墙或一个有趣的地点，互相拍照', tags: '["摄影","约会"]', mood_tags: '["浪漫","开心"]', icon: '📸' },
  { title: '一起制作晚餐', description: '从买菜到做完，分工合作做一顿晚餐', tags: '["烹饪","日常"]', mood_tags: '["浪漫","开心"]', icon: '👩‍🍳' },
  { title: '周末一起去爬山', description: '选一座不高的山，手牵手登顶看风景', tags: '["户外","运动"]', mood_tags: '["冒险","开心"]', icon: '⛰️' },
  { title: '在家建一个枕头城堡', description: '用所有的枕头和被子搭一个城堡，在里面看电影', tags: '["创意","在家"]', mood_tags: '["开心","浪漫"]', icon: '🏰' },
  { title: '一起看日出', description: '凌晨出发，带上一杯热咖啡，等待日出', tags: '["浪漫","户外"]', mood_tags: '["浪漫"]', icon: '🌅' },
  { title: '写一封手写信给对方', description: '不用电脑，用纸笔写一封信，寄给对方', tags: '["浪漫","写作"]', mood_tags: '["浪漫"]', icon: '💌' },
  { title: '一起去逛宜家', description: '走走样板间，想象未来一起的家', tags: '["日常","约会"]', mood_tags: '["开心","浪漫"]', icon: '🛋️' },
  { title: '做一份情侣问卷', description: '比如"36个问题让陌生人相爱"互相提问', tags: '["聊天","互相了解"]', mood_tags: '["浪漫","开心"]', icon: '❓' },
  { title: '一起学一支双人舞', description: '找一个双人舞教程，在客厅一起学', tags: '["舞蹈","学习"]', mood_tags: '["浪漫","开心"]', icon: '💃' },
  { title: '为对方做早餐', description: '比对方早起半小时，准备一份惊喜早餐', tags: '["烹饪","浪漫"]', mood_tags: '["浪漫","开心"]', icon: '🥞' },
  { title: '一起去游乐园', description: '坐过山车、吃棉花糖、拍傻傻的合照', tags: '["娱乐","约会"]', mood_tags: '["开心","冒险"]', icon: '🎢' },
  { title: '策划一次短途旅行', description: '一起挑选目的地，规划行程攻略', tags: '["旅行","规划"]', mood_tags: '["浪漫","开心"]', icon: '✈️' },
  { title: '一起做一个时间胶囊', description: '各自放入有意义的物品，约定一年后打开', tags: '["浪漫","回忆"]', mood_tags: '["浪漫"]', icon: '⏳' },
  { title: '给对方画肖像', description: '即使画得不好看，过程一定很有趣', tags: '["绘画","娱乐"]', mood_tags: '["开心","浪漫"]', icon: '🎨' },
  { title: '一起学做寿司', description: '买好材料，跟着视频学做寿司卷', tags: '["烹饪","学习"]', mood_tags: '["开心","浪漫"]', icon: '🍣' },
  { title: '去公园划船', description: '租一条小船，在湖上慢慢划', tags: '["户外","约会"]', mood_tags: '["浪漫","开心"]', icon: '🚣' },
  { title: '一起看一部恐怖片', description: '关灯盖毯子，害怕的时候抱在一起', tags: '["电影","在家"]', mood_tags: '["浪漫","开心"]', icon: '👻' },
  { title: '交换技能教学', description: '每人教对方一个自己擅长的技能', tags: '["学习","互动"]', mood_tags: '["开心"]', icon: '🔄' },
  { title: '一起去演唱会', description: '抢两张喜欢的歌手演唱会门票', tags: '["音乐","约会"]', mood_tags: '["开心","浪漫"]', icon: '🎵' },
  { title: '做一个情侣愿望清单', description: '写下未来想一起做的100件事', tags: '["规划","浪漫"]', mood_tags: '["浪漫","开心"]', icon: '📝' },
  { title: '一起去水族馆', description: '在水母和鱼群前拍一张背影合照', tags: '["约会","浪漫"]', mood_tags: '["浪漫","开心"]', icon: '🐠' },
  { title: '为对方搭配一套衣服', description: '每人给对方搭一套，然后穿出门吃饭', tags: '["穿搭","约会"]', mood_tags: '["开心","浪漫"]', icon: '👔' },
  { title: '一起看一部爱情电影', description: '选一部经典爱情片，看完聊聊感受', tags: '["电影","在家"]', mood_tags: '["浪漫"]', icon: '💕' },
  { title: '去天台看星星', description: '带上毯子，下载一个星座App，一起认星星', tags: '["浪漫","户外"]', mood_tags: '["浪漫"]', icon: '🌟' },
  { title: '一起整理房间', description: '两个人一起动手，让家焕然一新', tags: '["整理","日常"]', mood_tags: '["平静","开心"]', icon: '🏠' },
  { title: '做一个DIY手工', description: '一起做一个可以装饰家的手工品', tags: '["手工","创造"]', mood_tags: '["开心","浪漫"]', icon: '🎨' },
  { title: '去逛夜市小吃街', description: '从头吃到尾，每种小吃只买一份分着吃', tags: '["美食","约会"]', mood_tags: '["开心"]', icon: '🍢' },
  { title: '一起泡脚聊天', description: '准备一盆热水，一边泡脚一边聊天', tags: '["放松","日常"]', mood_tags: '["平静","浪漫"]', icon: '🦶' },
  { title: '互相给对方写诗', description: '不拘格式，写几句心里的感受', tags: '["写作","浪漫"]', mood_tags: '["浪漫"]', icon: '✒️' },
  { title: '一起看日落', description: '找一个视野好的地方，安静地看一场日落', tags: '["浪漫","户外"]', mood_tags: '["浪漫","平静"]', icon: '🌇' },
  { title: '一起种一棵植物', description: '去买一盆多肉或小盆栽，一起照顾它', tags: '["园艺","日常"]', mood_tags: '["平静","浪漫"]', icon: '🪴' },
  { title: '去咖啡馆约会', description: '找一家安静的咖啡馆，各自看书或聊天', tags: '["约会","放松"]', mood_tags: '["平静","浪漫"]', icon: '☕' },
  { title: '一起做公益', description: '捐衣服、去动物救助站做志愿者', tags: '["公益","约会"]', mood_tags: '["开心"]', icon: '🤲' },
  { title: '玩双人桌游', description: '挑一个双人桌游，度过一个悠闲的下午', tags: '["游戏","在家"]', mood_tags: '["开心","无聊"]', icon: '🎲' },
  { title: '一起去健身房', description: '互相监督，一起做力量训练或有氧', tags: '["运动","日常"]', mood_tags: '["开心"]', icon: '🏋️' },
  { title: '做一顿火锅', description: '买好锅底和涮菜，在家慢慢涮', tags: '["美食","在家"]', mood_tags: '["开心","浪漫"]', icon: '🍲' },
  { title: '一起学一首歌', description: '学一首可以合唱的歌，录下来留作纪念', tags: '["音乐","浪漫"]', mood_tags: '["浪漫","开心"]', icon: '🎤' },
  { title: '去花卉市场逛', description: '买一些鲜花和绿植，回家装饰房间', tags: '["购物","日常"]', mood_tags: '["开心","浪漫"]', icon: '🌷' },
  { title: '一起打羽毛球', description: '找个球场或空地，来一场友谊赛', tags: '["运动","户外"]', mood_tags: '["开心"]', icon: '🏸' },
  { title: '互相给对方按摩', description: '学几个简单的按摩手法，轮流给对方放松', tags: '["放松","日常"]', mood_tags: '["浪漫","平静"]', icon: '💆' },
  { title: '去看一场话剧', description: '买两张话剧票，感受现场表演的魅力', tags: '["艺术","约会"]', mood_tags: '["浪漫","开心"]', icon: '🎭' },
  { title: '一起学做咖啡拉花', description: '买一个奶泡器，在家练习拉花', tags: '["咖啡","学习"]', mood_tags: '["开心","浪漫"]', icon: '☕' },
  { title: '制定一个存钱目标', description: '一起制定一个共同的财务小目标', tags: '["理财","规划"]', mood_tags: '["平静"]', icon: '💰' },
  { title: '去水边散步', description: '在河边或海边手牵手散步聊天', tags: '["散步","浪漫"]', mood_tags: '["浪漫","平静"]', icon: '🌊' },
  { title: '一起烤饼干', description: '买好饼干模具，一起烤可爱的饼干', tags: '["烘焙","在家"]', mood_tags: '["开心","浪漫"]', icon: '🍪' },
  { title: '互相理发（简单的）', description: '比如修刘海，体验一下托尼老师的感觉', tags: '["日常","趣味"]', mood_tags: '["开心","冒险"]', icon: '✂️' },
  { title: '去做陶艺', description: '到陶艺工作室，一起捏杯子或花瓶', tags: '["手工","约会"]', mood_tags: '["浪漫","开心"]', icon: '🏺' },
  { title: '一起玩拼图', description: '买一个1000块的拼图，两人合作完成', tags: '["游戏","在家"]', mood_tags: '["平静","开心"]', icon: '🧩' },
  { title: '去城市周边一日游', description: '搜索周边冷门景点，开车或坐大巴去', tags: '["旅行","探索"]', mood_tags: '["冒险","开心"]', icon: '🚗' },
  { title: '写100个对方的优点', description: '交换纸条，写下对方的100个优点', tags: '["浪漫","写作"]', mood_tags: '["浪漫","开心"]', icon: '💝' },
  { title: '去钓鱼', description: '找一条河或湖，安静地坐着钓鱼聊天', tags: '["户外","放松"]', mood_tags: '["平静","浪漫"]', icon: '🎣' },
  { title: '一起布置房间', description: '挂灯串、贴照片墙、换新床品', tags: '["家居","日常"]', mood_tags: '["浪漫","开心"]', icon: '🏠' },
  { title: '看对方的童年照', description: '翻出小时候的照片，分享背后的故事', tags: '["聊天","回忆"]', mood_tags: '["开心","浪漫"]', icon: '📷' },
  { title: '去温泉度假村', description: '找一个温泉，泡汤放松', tags: '["放松","旅行"]', mood_tags: '["浪漫","平静"]', icon: '♨️' },
  { title: '一起学一门外语', description: '每天学5个单词，互相考核', tags: '["学习","日常"]', mood_tags: '["平静"]', icon: '📖' },
  { title: '去电玩城', description: '投篮机、夹娃娃、赛车…玩遍所有项目', tags: '["游戏","约会"]', mood_tags: '["开心"]', icon: '🕹️' },
  { title: '一起做瑜伽', description: '铺开瑜伽垫，跟着视频做双人瑜伽', tags: '["运动","在家"]', mood_tags: '["平静","浪漫"]', icon: '🧘' },
  { title: '去天文馆', description: '在球幕影院里看星星，感受宇宙的浪漫', tags: '["科学","约会"]', mood_tags: '["浪漫","平静"]', icon: '🔭' },
  { title: '一起清理衣柜', description: '断舍离，给对方出谋划策', tags: '["整理","日常"]', mood_tags: '["平静","开心"]', icon: '👗' },
  { title: '分享彼此的梦想', description: '坐下来认真聊聊：你最想实现什么梦想？', tags: '["聊天","互相了解"]', mood_tags: '["浪漫","平静"]', icon: '💭' },
  { title: '去滑冰场', description: '手牵手在冰上滑行（或摔跤）', tags: '["运动","约会"]', mood_tags: '["开心","冒险"]', icon: '⛸️' },
  { title: '一起制作一本相册', description: '把手机里的合照冲洗出来，做成相册', tags: '["手工","回忆"]', mood_tags: '["浪漫","开心"]', icon: '📔' },
  { title: '去果园采摘', description: '摘草莓、樱桃、葡萄，体验田园乐趣', tags: '["户外","美食"]', mood_tags: '["开心","冒险"]', icon: '🍓' },
  { title: '一起重新装修一个角落', description: '选家里的一个角落，一起改造升级', tags: '["家居","创造"]', mood_tags: '["开心","浪漫"]', icon: '🔨' },
  { title: '给对方做心理测试', description: '找一个MBTI或心理测试，一起做一起分析', tags: '["自我探索","聊天"]', mood_tags: '["开心","平静"]', icon: '🔍' },
  { title: '去听爵士现场', description: '找一个爵士酒吧，享受音乐和美酒', tags: '["音乐","约会"]', mood_tags: '["浪漫"]', icon: '🎷' },
  { title: '一起堆雪人', description: '冬天下雪时，去户外堆一个雪人', tags: '["户外","玩雪"]', mood_tags: '["开心","浪漫"]', icon: '⛄' },
  { title: '一起折千纸鹤', description: '一起折纸鹤，许下共同的愿望', tags: '["手工","浪漫"]', mood_tags: '["浪漫","平静"]', icon: '🕊️' },
  { title: '去逛家居店', description: '一起逛家居店，聊未来的装修风格', tags: '["购物","约会"]', mood_tags: '["开心","浪漫"]', icon: '🏪' },
  { title: '一起参加烘焙课', description: '报名一节烘焙课程，一起学做蛋糕', tags: '["学习","烘焙"]', mood_tags: '["开心","浪漫"]', icon: '🎂' },
  { title: '各自的独处时光', description: '待在同一个空间，但各做各的事', tags: '["日常","独立"]', mood_tags: '["平静"]', icon: '🤫' },
  { title: '去奥特莱斯购物', description: '一起逛街，给对方挑打折好货', tags: '["购物","约会"]', mood_tags: '["开心"]', icon: '🛍️' },
  { title: '一起养一只宠物', description: '或者一起去撸猫咖啡馆', tags: '["动物","日常"]', mood_tags: '["开心","浪漫"]', icon: '🐱' },
  { title: '玩真心话大冒险', description: '两人版的真心话大冒险，增进了解', tags: '["游戏","聊天"]', mood_tags: '["开心","浪漫"]', icon: '🎯' },
  { title: '去城市的高楼看全景', description: '找一个观景台，俯瞰整个城市', tags: '["约会","浪漫"]', mood_tags: '["浪漫","开心"]', icon: '🏙️' },
  { title: '一起做Spa', description: '预约一次双人Spa，彻底放松身心', tags: '["放松","浪漫"]', mood_tags: '["浪漫","平静"]', icon: '🧖' },
  { title: '写恋爱时间线', description: '从认识到现在，写下重要的日期和回忆', tags: '["回忆","写作"]', mood_tags: '["浪漫"]', icon: '📜' },
  { title: '去果园或农场', description: '体验采摘或喂动物', tags: '["户外","自然"]', mood_tags: '["开心","冒险"]', icon: '🌾' },
  { title: '一起打台球', description: '去台球厅，来一局轻松的比赛', tags: '["运动","约会"]', mood_tags: '["开心"]', icon: '🎱' },
  { title: '互相当对方的发型师', description: '给对方编辫子、做造型', tags: '["趣味","日常"]', mood_tags: '["开心","浪漫"]', icon: '💇' },
  { title: '去KTV唱一下午', description: '两人包一个小包厢，尽情唱歌', tags: '["音乐","约会"]', mood_tags: '["开心"]', icon: '🎤' },
  { title: '一起捐赠旧物', description: '整理不需要的衣服书籍，一起送去捐赠', tags: '["公益","整理"]', mood_tags: '["开心","平静"]', icon: '📦' },
  { title: '学习给对方拍照', description: '学习基础摄影技巧，把对方拍得更好看', tags: '["摄影","学习"]', mood_tags: '["开心","浪漫"]', icon: '📷' },
  { title: '去水上乐园', description: '夏天一起去玩水，找回童年的快乐', tags: '["户外","娱乐"]', mood_tags: '["开心","冒险"]', icon: '🏖️' },
  { title: '一起做春节大扫除', description: '迎接新年的仪式感', tags: '["整理","节日"]', mood_tags: '["开心","平静"]', icon: '🧹' },
  { title: '去二手市场砍价', description: '一人砍价一人配合，淘喜欢的旧物', tags: '["购物","趣味"]', mood_tags: '["冒险","开心"]', icon: '💰' },
  { title: '一起学做冰淇淋', description: '夏天自己动手做冰淇淋', tags: '["烹饪","夏季"]', mood_tags: '["开心","浪漫"]', icon: '🍦' },
  { title: '去马拉松加油', description: '参加或围观一场马拉松，感受运动氛围', tags: '["运动","户外"]', mood_tags: '["开心","冒险"]', icon: '🏃' },
  { title: '一起装饰圣诞树', description: '圣诞节一起装饰房间和圣诞树', tags: '["节日","家居"]', mood_tags: '["浪漫","开心"]', icon: '🎄' },
  { title: '去漂流', description: '夏天找一个漂流景区，一起尖叫', tags: '["户外","运动"]', mood_tags: '["冒险","开心"]', icon: '🛶' },
  { title: '互相分享歌单', description: '交换近期最爱的歌单，一起听', tags: '["音乐","聊天"]', mood_tags: '["浪漫","平静"]', icon: '🎧' },
  { title: '一起做理财规划', description: '聊聊财务目标，制定存钱和投资计划', tags: '["理财","规划"]', mood_tags: '["平静"]', icon: '📊' },
  { title: '去密室逃脱', description: '两人挑战密室逃脱，考验默契', tags: '["游戏","约会"]', mood_tags: '["冒险","开心"]', icon: '🔐' },
  { title: '一起写2026年计划', description: '在年初写下共同的目标和愿景', tags: '["规划","写作"]', mood_tags: '["平静","浪漫"]', icon: '📝' },
  { title: '去果园酿果酒', description: '用采摘的水果一起酿一瓶果酒', tags: '["手工","美食"]', mood_tags: '["浪漫","开心"]', icon: '🍷' },
  { title: '一起做皮具DIY', description: '去手作工坊，做一对情侣皮手环', tags: '["手工","浪漫"]', mood_tags: '["浪漫","开心"]', icon: '🧵' },
  { title: '去看一场烟花', description: '找一场烟花秀，在漫天烟花下拥吻', tags: '["浪漫","节日"]', mood_tags: '["浪漫"]', icon: '🎆' },
  { title: '去深夜食堂', description: '半夜出去找一家还在营业的小店', tags: '["美食","冒险"]', mood_tags: '["冒险","浪漫"]', icon: '🍜' },
  { title: '一起做一个vlog', description: '记录一天的约会，剪辑成vlog', tags: '["视频","创造"]', mood_tags: '["开心","浪漫"]', icon: '🎬' },
  { title: '互相监督早睡早起', description: '建立健康作息，互相打卡叫早', tags: '["健康","日常"]', mood_tags: '["平静"]', icon: '⏰' },
];

// ========== 好友活动（100+条）==========
const friendActivities = [
  { title: '桌游挑战之夜', description: '拿出所有桌游，举办一场桌游马拉松', tags: '["桌游","派对"]', mood_tags: '["开心"]', icon: '🎲' },
  { title: '火锅聚会', description: '准备锅底和各种涮菜，一边吃一边聊', tags: '["美食","聚会"]', mood_tags: '["开心"]', icon: '🍲' },
  { title: '城市探店', description: '挑选几家网红店，一天全部打卡', tags: '["探索","美食"]', mood_tags: '["冒险","开心"]', icon: '🔍' },
  { title: '一起去看电影', description: '选一部新上映的大片，买好爆米花', tags: '["电影","聚会"]', mood_tags: '["开心","无聊"]', icon: '🍿' },
  { title: '组织一场烧烤趴', description: '在公园或天台办一场烧烤Party', tags: '["美食","户外"]', mood_tags: '["开心"]', icon: '🥩' },
  { title: '密室逃脱挑战', description: '团队合作，一起破解密室谜题', tags: '["游戏","解谜"]', mood_tags: '["冒险","开心"]', icon: '🔐' },
  { title: 'KTV之夜', description: '包一个大包厢，从经典唱到新歌', tags: '["音乐","聚会"]', mood_tags: '["开心"]', icon: '🎤' },
  { title: '一起去露营', description: '带上帐篷和食材，去郊外露营看星星', tags: '["户外","旅行"]', mood_tags: '["冒险","开心"]', icon: '⛺' },
  { title: '剧本杀', description: '选一个好剧本，各自扮演角色推理', tags: '["游戏","解谜"]', mood_tags: '["冒险","开心"]', icon: '🕵️' },
  { title: 'DIY手工派对', description: '准备好材料，一起做手工', tags: '["手工","创造"]', mood_tags: '["开心","平静"]', icon: '🎨' },
  { title: '一起去骑行', description: '骑共享单车探索城市绿道', tags: '["运动","户外"]', mood_tags: '["冒险","开心"]', icon: '🚲' },
  { title: '美食一条街', description: '从街头吃到街尾，不醉不归', tags: '["美食","聚会"]', mood_tags: '["开心"]', icon: '🍢' },
  { title: '一起打篮球', description: '约一个球场，三对三斗牛', tags: '["运动","户外"]', mood_tags: '["开心"]', icon: '🏀' },
  { title: '周末早午餐', description: '找一家美美的brunch店，享受悠闲周末', tags: '["美食","聚会"]', mood_tags: '["开心","平静"]', icon: '🥐' },
  { title: '电竞之夜', description: '组队开黑，五连坐', tags: '["游戏","电子"]', mood_tags: '["开心"]', icon: '🎮' },
  { title: '逛博物馆', description: '一起去博物馆涨知识', tags: '["文化","外出"]', mood_tags: '["平静","开心"]', icon: '🏛️' },
  { title: '组织运动会', description: '羽毛球、乒乓球、踢毽子，来个趣味运动会', tags: '["运动","户外"]', mood_tags: '["开心"]', icon: '🏅' },
  { title: '一起参加音乐节', description: '抢早鸟票，在草地上听音乐蹦迪', tags: '["音乐","户外"]', mood_tags: '["开心","冒险"]', icon: '🎪' },
  { title: '去蹦床公园', description: '在蹦床上跳来跳去，释放压力', tags: '["运动","娱乐"]', mood_tags: '["开心"]', icon: '🤸' },
  { title: '举办主题派对', description: '复古、睡衣、制服…定个主题开派对', tags: '["派对","创意"]', mood_tags: '["开心"]', icon: '🎉' },
  { title: '一起去滑雪', description: '冬天组队去雪场滑雪', tags: '["运动","冬季"]', mood_tags: '["冒险","开心"]', icon: '⛷️' },
  { title: '玩水枪大战', description: '夏天买水枪，在公园打水仗', tags: '["户外","夏季"]', mood_tags: '["开心"]', icon: '🔫' },
  { title: '去鬼屋探险', description: '互相壮胆，看看谁叫得最大声', tags: '["娱乐","冒险"]', mood_tags: '["冒险","开心"]', icon: '👻' },
  { title: '一起学画画', description: '去画室上一节集体绘画课', tags: '["绘画","学习"]', mood_tags: '["平静","开心"]', icon: '🖌️' },
  { title: '周末市集之旅', description: '逛手作市集、跳蚤市场', tags: '["购物","探索"]', mood_tags: '["开心","冒险"]', icon: '🏪' },
  { title: '组织读书会', description: '每人推荐一本书，轮流分享心得', tags: '["阅读","社交"]', mood_tags: '["平静"]', icon: '📚' },
  { title: '一起去攀岩', description: '去室内攀岩馆挑战自己', tags: '["运动","挑战"]', mood_tags: '["冒险","开心"]', icon: '🧗' },
  { title: '办一场厨艺大赛', description: '每人做一道菜，投票选出最佳', tags: '["烹饪","比赛"]', mood_tags: '["开心"]', icon: '🍳' },
  { title: '去动物园', description: '和朋友们一起看动物，拍搞怪照片', tags: '["户外","娱乐"]', mood_tags: '["开心"]', icon: '🦁' },
  { title: '骑行到城市边缘', description: '租车骑到平时不会去的地方', tags: '["运动","探索"]', mood_tags: '["冒险","开心"]', icon: '🚵' },
  { title: '一起拼乐高', description: '买一个大乐高套装，分工合作', tags: '["手工","合作"]', mood_tags: '["平静","开心"]', icon: '🧱' },
  { title: '打保龄球', description: '不管打得好不好，开心就好', tags: '["运动","聚会"]', mood_tags: '["开心"]', icon: '🎳' },
  { title: '组织一场知识竞赛', description: '每人事先出10道题，组队PK', tags: '["游戏","学习"]', mood_tags: '["开心"]', icon: '🧠' },
  { title: '去水上世界', description: '夏天去水上乐园玩一天', tags: '["户外","夏季"]', mood_tags: '["开心","冒险"]', icon: '🌊' },
  { title: '一起做义工', description: '去动物救助站或社区服务', tags: '["公益","社交"]', mood_tags: '["开心"]', icon: '🤝' },
  { title: '城市定向越野', description: '设置打卡点，在城市里来一场定向越野', tags: '["运动","探索"]', mood_tags: '["冒险","开心"]', icon: '🧭' },
  { title: '看一场球赛', description: '买票去看足球或篮球比赛', tags: '["体育","聚会"]', mood_tags: '["开心"]', icon: '⚽' },
  { title: '去泡温泉', description: '冬天约朋友去泡温泉', tags: '["放松","冬季"]', mood_tags: '["平静","开心"]', icon: '♨️' },
  { title: '一起堆乐高城市', description: '每个人负责一个区域', tags: '["手工","创意"]', mood_tags: '["平静","开心"]', icon: '🏗️' },
  { title: '去跳广场舞', description: '自嘲式地加入广场舞队伍', tags: '["运动","趣味"]', mood_tags: '["开心"]', icon: '💃' },
  { title: '举办枕头大战', description: '在客厅来一场软绵绵的枕头大战', tags: '["游戏","派对"]', mood_tags: '["开心"]', icon: '🛏️' },
  { title: '一起去看日出', description: '约凌晨4点出发，一起等日出', tags: '["户外","浪漫"]', mood_tags: '["冒险","浪漫"]', icon: '🌅' },
  { title: '去猫咖撸猫', description: '找个猫咖，一起被猫咪治愈', tags: '["动物","放松"]', mood_tags: '["开心","平静"]', icon: '🐱' },
  { title: '一起做泡菜或酿酒', description: '买好材料，一起动手做发酵食品', tags: '["烹饪","手工"]', mood_tags: '["开心","平静"]', icon: '🫙' },
  { title: '去听一场脱口秀', description: '买票去看线下脱口秀', tags: '["喜剧","娱乐"]', mood_tags: '["开心"]', icon: '🎙️' },
  { title: '一起过生日', description: '给朋友筹备一个惊喜生日派对', tags: '["派对","庆祝"]', mood_tags: '["开心","浪漫"]', icon: '🎂' },
  { title: '去跳蚤市场摆摊', description: '清理不用的东西，一起摆摊卖掉', tags: '["创业","趣味"]', mood_tags: '["冒险","开心"]', icon: '🏷️' },
  { title: '一起学一门乐器', description: '买个尤克里里，一起学弹一首歌', tags: '["音乐","学习"]', mood_tags: '["开心","平静"]', icon: '🎸' },
  { title: '去城市夜景最美的地方', description: '搜索城市夜景机位，一起去拍照', tags: '["摄影","探索"]', mood_tags: '["浪漫","冒险"]', icon: '🌃' },
  { title: '组织跳蚤交换会', description: '每人带闲置物品来交换', tags: '["交换","社交"]', mood_tags: '["开心","平静"]', icon: '🔄' },
  { title: '去海边捡贝壳', description: '沿着海岸线散步，收集美丽的贝壳', tags: '["户外","自然"]', mood_tags: '["平静","开心"]', icon: '🐚' },
  { title: '一起打乒乓球', description: '找一张乒乓球桌，车轮战', tags: '["运动","聚会"]', mood_tags: '["开心"]', icon: '🏓' },
  { title: '做一次美食测评', description: '买不同品牌的同一食物，盲测打分', tags: '["美食","趣味"]', mood_tags: '["开心","无聊"]', icon: '🥷' },
  { title: '去采摘园', description: '摘草莓、樱桃、葡萄，边摘边吃', tags: '["户外","美食"]', mood_tags: '["开心","冒险"]', icon: '🍓' },
  { title: '一起做瑜伽', description: '在公园或客厅铺开垫子做瑜伽', tags: '["运动","放松"]', mood_tags: '["平静","开心"]', icon: '🧘' },
  { title: '拍一部微电影', description: '用手机拍一部小短片，自编自导自演', tags: '["视频","创造"]', mood_tags: '["开心","冒险"]', icon: '🎬' },
  { title: '去大学旁听一堂课', description: '混进大学教室，假装是学生', tags: '["学习","冒险"]', mood_tags: '["冒险","开心"]', icon: '🏫' },
  { title: '一起放风筝', description: '买一个风筝，在公园里放起来', tags: '["户外","童年"]', mood_tags: '["开心","平静"]', icon: '🪁' },
  { title: '组一支临时乐队', description: '即使没有音乐基础，摇沙锤也算', tags: '["音乐","趣味"]', mood_tags: '["开心"]', icon: '🥁' },
  { title: '去射击场', description: '体验射击或射箭', tags: '["运动","冒险"]', mood_tags: '["冒险","开心"]', icon: '🏹' },
  { title: '做一个时间胶囊', description: '每人放一样东西，约定五年后一起打开', tags: '["浪漫","回忆"]', mood_tags: '["浪漫","平静"]', icon: '⏳' },
  { title: '去早市吃早餐', description: '赶早去菜市场吃豆浆油条', tags: '["美食","生活"]', mood_tags: '["开心","平静"]', icon: '🥟' },
  { title: '一起学魔术', description: '每人学一个魔术，然后互相表演', tags: '["学习","娱乐"]', mood_tags: '["开心","无聊"]', icon: '🪄' },
  { title: '去植物园野餐', description: '准备食物和野餐垫，在植物园躺一下午', tags: '["户外","放松"]', mood_tags: '["平静","开心"]', icon: '🌿' },
  { title: '做一次街头采访', description: '准备几个有趣的问题，去街头采访路人', tags: '["社交","创造"]', mood_tags: '["冒险","开心"]', icon: '🎤' },
  { title: '一起做木工', description: '去木工坊做一个小板凳或小架子', tags: '["手工","学习"]', mood_tags: '["平静","开心"]', icon: '🪚' },
  { title: '去溜冰场', description: '不管是轮滑还是真冰，一起滑起来', tags: '["运动","娱乐"]', mood_tags: '["开心","冒险"]', icon: '⛸️' },
  { title: '组织旧物改造大赛', description: '每人带一件旧物，看谁能改造得最棒', tags: '["手工","比赛"]', mood_tags: '["开心","创造"]', icon: '♻️' },
  { title: '去天文台看星星', description: '预约天文台开放日，看土星环', tags: '["科学","浪漫"]', mood_tags: '["浪漫","平静"]', icon: '🔭' },
  { title: '一起学做咖啡', description: '找一个咖啡体验课，学习冲咖啡', tags: '["咖啡","学习"]', mood_tags: '["开心","平静"]', icon: '☕' },
  { title: '去溜冰场滑冰', description: '冬天去户外冰场滑冰', tags: '["运动","冬季"]', mood_tags: '["开心","冒险"]', icon: '🧊' },
  { title: '举办电影之夜', description: '投票选三部电影，通宵看', tags: '["电影","派对"]', mood_tags: '["开心","无聊"]', icon: '🎬' },
  { title: '一起装饰节日', description: '万圣节刻南瓜、春节写对联', tags: '["手工","节日"]', mood_tags: '["开心","浪漫"]', icon: '🎃' },
  { title: '去拳击馆', description: '戴上拳套，来一场友谊拳击', tags: '["运动","发泄"]', mood_tags: '["开心","冒险"]', icon: '🥊' },
  { title: '制作一本友谊相册', description: '收集大家的合照，做成一本相册', tags: '["手工","回忆"]', mood_tags: '["开心","浪漫"]', icon: '📸' },
  { title: '去台球厅', description: '来一场台球友谊赛', tags: '["运动","聚会"]', mood_tags: '["开心","平静"]', icon: '🎱' },
  { title: '一起做手工皂', description: '融化皂基，加入精油和干花', tags: '["手工","创造"]', mood_tags: '["平静","开心"]', icon: '🧼' },
  { title: '去蹦极或跳伞', description: '挑战极限，一起感受肾上腺素', tags: '["极限运动","挑战"]', mood_tags: '["冒险"]', icon: '🪂' },
  { title: '玩谁是卧底', description: '经典聚会游戏，考验演技', tags: '["游戏","派对"]', mood_tags: '["开心"]', icon: '🕵️' },
  { title: '去啤酒节', description: '找一场啤酒节或美食节，一起嗨', tags: '["美食","节日"]', mood_tags: '["开心"]', icon: '🍺' },
  { title: '一起做陶艺', description: '在陶艺工作室捏陶，看谁做得最抽象', tags: '["手工","艺术"]', mood_tags: '["平静","开心"]', icon: '🏺' },
  { title: '去高尔夫练习场', description: '体验挥杆的乐趣', tags: '["运动","体验"]', mood_tags: '["开心","平静"]', icon: '⛳' },
  { title: '一起学做寿司', description: '准备各种食材，卷起来', tags: '["烹饪","学习"]', mood_tags: '["开心"]', icon: '🍣' },
  { title: '去水上桨板', description: '夏天玩SUP桨板，掉水里也是一种乐趣', tags: '["运动","夏季"]', mood_tags: '["冒险","开心"]', icon: '🏄' },
  { title: '组织一个才艺表演', description: '每人准备一个节目，办一场小型晚会', tags: '["表演","派对"]', mood_tags: '["开心"]', icon: '🎭' },
  { title: '去二手唱片店', description: '一起淘黑胶唱片，交流音乐品味', tags: '["音乐","购物"]', mood_tags: '["平静","开心"]', icon: '💿' },
  { title: '一起写新年计划', description: '喝杯咖啡，分享彼此的新年目标', tags: '["规划","社交"]', mood_tags: '["平静","开心"]', icon: '📝' },
  { title: '去打保龄球', description: '记分板上一定很有趣', tags: '["运动","聚会"]', mood_tags: '["开心"]', icon: '🎳' },
  { title: '去古城或古镇一日游', description: '探索附近的古镇，拍古风照片', tags: '["旅行","探索"]', mood_tags: '["冒险","开心"]', icon: '🏚️' },
  { title: '一起做冰淇淋', description: '夏天自制冰淇淋，diy各种口味', tags: '["美食","夏季"]', mood_tags: '["开心"]', icon: '🍧' },
  { title: '去美术馆看展', description: '看一个新开的展览，各自分享感受', tags: '["艺术","文化"]', mood_tags: '["平静","开心"]', icon: '🖼️' },
  { title: '举办卡拉OK大赛', description: '手机打分，看谁得分最高', tags: '["音乐","比赛"]', mood_tags: '["开心"]', icon: '🎶' },
  { title: '去河边钓鱼', description: '租钓竿，在河边安静地钓鱼', tags: '["户外","放松"]', mood_tags: '["平静","开心"]', icon: '🎣' },
  { title: '一起拼1000片拼图', description: '分工合作，完成一幅大拼图', tags: '["游戏","合作"]', mood_tags: '["平静","开心"]', icon: '🧩' },
  { title: '去漫展', description: '穿上Cos服或只是逛展', tags: '["动漫","文化"]', mood_tags: '["开心","冒险"]', icon: '👘' },
  { title: '做一顿各国美食宴', description: '每人负责一个国家的一道菜', tags: '["烹饪","聚会"]', mood_tags: '["开心"]', icon: '🌍' },
];

/**
 * 插入种子数据
 */
function seedData(db) {
  console.log('🌱 开始插入种子数据...');

  const insertCategory = db.prepare(
    'INSERT INTO categories (name, icon, description, sort_order) VALUES (?, ?, ?, ?)'
  );
  const insertActivity = db.prepare(
    `INSERT INTO activities (category_id, title, description, tags, mood_tags, icon, is_premium)
     VALUES (?, ?, ?, ?, ?, ?, ?)`
  );

  const seedAll = db.transaction(() => {
    // 插入分类
    const categoryMap = {};
    for (const cat of categoriesData) {
      const result = insertCategory.run(cat.name, cat.icon, cat.description, cat.sort_order);
      categoryMap[cat.name] = result.lastInsertRowid;
      console.log(`  📁 分类: ${cat.icon} ${cat.name} (id: ${result.lastInsertRowid})`);
    }

    // 插入独处活动
    for (const activity of soloActivities) {
      insertActivity.run(
        categoryMap['独处'],
        activity.title,
        activity.description,
        activity.tags,
        activity.mood_tags,
        activity.icon,
        0
      );
    }
    console.log(`  ✅ 独处: ${soloActivities.length} 条活动`);

    // 插入情侣活动
    for (const activity of coupleActivities) {
      insertActivity.run(
        categoryMap['情侣'],
        activity.title,
        activity.description,
        activity.tags,
        activity.mood_tags,
        activity.icon,
        0
      );
    }
    console.log(`  ✅ 情侣: ${coupleActivities.length} 条活动`);

    // 插入好友活动
    for (const activity of friendActivities) {
      insertActivity.run(
        categoryMap['好友'],
        activity.title,
        activity.description,
        activity.tags,
        activity.mood_tags,
        activity.icon,
        0
      );
    }
    console.log(`  ✅ 好友: ${friendActivities.length} 条活动`);
  });

  seedAll();
  const total = db.prepare('SELECT COUNT(*) as cnt FROM activities').get();
  console.log(`🎉 种子数据插入完成！总计 ${total.cnt} 条活动`);
}

module.exports = { seedData };
